Fix URL to match job title for communications editor job
publiccodenet/publiccode.net pull request #188
Opened 2021-05-17 10:57 UTC by ElenaFdR

This should help with SEO and remove any possibility for confusion re the job title.

2021-05-19 11:28 UTC, bvhme approved these changes

2021-05-19 11:29 UTC, bvhme requested changes
Front matter is not formatted correctly

2021-05-25 11:56 UTC, ElenaFdR commented
Travis is breaking on a Google form that loads in the browser.

2021-05-27 14:08 UTC, Ainali approved these changes

2021-05-27 14:11 UTC, bvhme approved these changes

2021-05-27 14:11 UTC, merged